# Generated by Django 4.1.7 on 2023-04-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivos', models.CharField(max_length=50)),
                ('confirmacion', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CargoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActual', models.DateTimeField()),
                ('fechaProgramada', models.DateTimeField()),
                ('fechaMaxima', models.DateTimeField()),
                ('activa', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('recomendaciones', models.CharField(max_length=100)),
                ('informacionAdicional', models.CharField(max_length=100)),
                ('idCita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.cita')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelativoSar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cai', models.CharField(max_length=100)),
                ('rangoInicial', models.PositiveIntegerField()),
                ('rangoFinal', models.PositiveIntegerField()),
                ('consecutivo', models.PositiveIntegerField()),
                ('fechaLimiteEmision', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('activo', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=20)),
                ('activo', models.PositiveSmallIntegerField()),
                ('idCargoEmpleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.cargoempleado')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaProgramada', models.DateTimeField()),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('disponibilidad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField()),
                ('activo', models.PositiveSmallIntegerField()),
                ('stockActual', models.PositiveIntegerField()),
                ('stockMinimo', models.PositiveIntegerField()),
                ('stockMaximo', models.PositiveIntegerField()),
                ('costoCompra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idImpuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('documento', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noFactura', models.CharField(max_length=50)),
                ('fechaFacturacion', models.CharField(blank=True, max_length=25, null=True)),
                ('efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=25, null=True)),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('activa', models.PositiveSmallIntegerField(default=1)),
                ('idConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.consulta')),
                ('idCorrelativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.correlativosar')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado')),
                ('idMetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.metododepago')),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('idImpuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto')),
                ('idsubtipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.subtipo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('longitud', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('metodoConservacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('activo', models.PositiveSmallIntegerField()),
                ('bloqueado', models.PositiveSmallIntegerField()),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('intentos', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sesion', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('idEmpleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diasTratamiento', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('idAutorizacionPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.autorizacionpaciente')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('idTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RecaudoDetalleTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecaudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.recaudo')),
                ('idTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RecaudoDetalleMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento')),
                ('idRecaudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.recaudo')),
            ],
        ),
        migrations.CreateModel(
            name='RecaudoDetalleExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.examen')),
                ('idRecaudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.recaudo')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idmedicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='idTipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipodocumentos'),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
                ('idTipoMuestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipomuestra')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.proveedor'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo'),
        ),
        migrations.CreateModel(
            name='ImpuestoHitorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idImpuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('activo', models.PositiveSmallIntegerField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='idLaboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.laboratorios'),
        ),
        migrations.AddField(
            model_name='examen',
            name='idMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.muestra'),
        ),
        migrations.AddField(
            model_name='examen',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo'),
        ),
        migrations.CreateModel(
            name='EnfermedadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEnfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.enfermedad')),
                ('idSintoma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.sintoma')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idEspecialidadMedico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.especialidadmedico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='idTipoDocumentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipodocumentos'),
        ),
        migrations.CreateModel(
            name='DiagnosticoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDiagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.diagnostico')),
                ('idEnfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='CostoHistoricoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idmedicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idConsulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.consulta')),
                ('idDiagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.diagnostico')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente'),
        ),
    ]
