# Generated by Django 4.1.7 on 2023-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pagado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examen',
            name='pagado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='pagado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
