# Generated by Django 4.1.7 on 2023-07-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_recaudo_cambio_recaudo_descuento_recaudo_iddescuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pantallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.PositiveSmallIntegerField()),
                ('idAcciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.acciones')),
                ('idCargoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.cargoempleado')),
                ('idPantallas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.pantallas')),
            ],
        ),
    ]
